# Generated by Django 4.2 on 2024-02-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('start_date_time', models.DateTimeField()),
                ('price', models.FloatField()),
                ('min_users', models.IntegerField()),
                ('max_users', models.IntegerField()),
            ],
        ),
    ]
